#!/bin/bash
if [ "$1" = "" ]
then
	echo "Usage: install-deps <server>"
	exit 1
fi
set -ex

# first deps
ssh root@$1 'set -ex; apt-get update'
ssh root@$1 'set -ex; apt-get install -y software-properties-common curl git htop tree nginx mongodb ssl-cert'

# docker
ssh root@$1 'set -ex; apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D'
ssh root@$1 'set -ex; echo "deb https://apt.dockerproject.org/repo ubuntu-wily main" > /etc/apt/sources.list.d/docker.list'

# haxe
ssh root@$1 'set -ex; add-apt-repository -y ppa:haxe/releases'

# node
ssh root@$1 'set -ex; curl -sL https://deb.nodesource.com/setup_4.x | bash -'

# second deps
ssh root@$1 'set -ex; apt-get install -y neko haxe nodejs docker-engine'

# haxe deps and tora
ssh root@$1 'set -ex; haxelib setup /usr/share/haxe/lib'
ssh root@$1 'set -ex; mkdir -p /var/git && git clone https://github.com/HaxeFoundation/tora /var/git/tora && cd /var/git/tora && haxe tora.hxml'

