#!/bin/bash
server=new.maxikali.com
if [ "$1" != "" ]
then
	echo "Usage: install-deps [server]"
	echo "Using custom server $1"
	server=$1
fi
set -ex

# first deps
ssh root@$server 'set -ex; apt-get update'
ssh root@$server 'set -ex; apt-get install -y software-properties-common curl git htop tree nginx mongodb ssl-cert'

# docker
ssh root@$server 'set -ex; apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D'
ssh root@$server 'set -ex; echo "deb https://apt.dockerproject.org/repo ubuntu-wily main" > /etc/apt/sources.list.d/docker.list'

# haxe
ssh root@$server 'set -ex; add-apt-repository -y ppa:haxe/releases'

# node
ssh root@$server 'set -ex; curl -sL https://deb.nodesource.com/setup_4.x | bash -'

# second dserverps
ssh root@$server 'set -ex; apt-get install -y neko haxe nodejs docker-engine'

# haxe depserver and tora
ssh root@$server 'set -ex; haxelib setup /usr/share/haxe/lib'
ssh root@$server 'set -ex; mkdir -p /var/git && git clone https://github.com/HaxeFoundation/tora /var/git/tora && cd /var/git/tora && haxe tora.hxml'

