#!/bin/bash
if [ "$1" = "" ]
then
	echo "Usage: restart-all <server>"
	exit 1
fi
set -ex

ssh root@$1 'set -ex; systemctl restart robrt && nginx -s reload && sleep 1 && systemctl status robrt && systemctl status nginx'
